workflow Thu Aug  1 13:22:28 CDT 2024

diff --git a/.github/workflows/images-build.yml b/.github/workflows/images-build.yml
--- a/.github/workflows/images-build.yml
+++ b/.github/workflows/images-build.yml
@@ -25,10 +25,14 @@ jobs:
   job-images-build:
     runs-on: [ self-hosted, almalinux ]
     steps:
+      - name: check and mark secrets
+        run: |
+          echo "::add-mask::$SSH_PUBLIC_KEY"
+          echo "::add-mask::$SSH_PRIVATE_KEY"
+          [ -n "$SSH_PUBLIC_KEY" ] || ( echo "Required variable unset SSH_PUBLIC_KEY" ; exit 1 )
+          [ -n "$SSH_PRIVATE_KEY" ] || ( echo "Required variable unset SSH_PRIVATE_KEY" ; exit 1 )
       - name: secrets install ssh key
         run: |
-          [ -n "${{ secrets.SSH_PUBLIC_KEY }}" ] || ( echo "Required variable unset SSH_PUBLIC_KEY" ; exit 1 )
-          [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ] || ( echo "Required variable unset SSH_PRIVATE_KEY" ; exit 1 )
           mkdir -p ${HOME}/.ssh
           chmod 0700 ${HOME}/.ssh
           touch ${HOME}/.ssh/id_ed25519.pub
@@ -38,10 +42,10 @@ jobs:
           touch ${HOME}/.ssh/config
           chmod 0644 ${HOME}/.ssh/config
           cat >${HOME}/.ssh/id_ed25519.pub <<EOF
-          ${{ secrets.SSH_PUBLIC_KEY }}
+          $SSH_PUBLIC_KEY
           EOF
           cat >${HOME}/.ssh/id_ed25519 <<EOF
-          ${{ secrets.SSH_PRIVATE_KEY }}
+          $SSH_PRIVATE_KEY
           EOF
           if ! grep -q -e '.ssh/id_ed25519$' ${HOME}/.ssh/config; then
             printf '\nHost *\n  IdentitiesOnly yes\n  IdentityFile %s\n\n%s' "${HOME}/.ssh/id_ed25519" "$(cat ${HOME}/.ssh/config)" >${HOME}/.ssh/config
