workflow Thu Aug  1 13:41:35 CDT 2024

diff --git a/.github/workflows/images-build.yml b/.github/workflows/images-build.yml
--- a/.github/workflows/images-build.yml
+++ b/.github/workflows/images-build.yml
@@ -27,8 +27,10 @@ jobs:
     steps:
       - name: check environment
         run: |
-          [ -n "${{ vars.SSH_PUBLIC_KEY }}" ] && echo "::add-mask::${{ vars.SSH_PUBLIC_KEY }}" || ( echo "Required variable unset SSH_PUBLIC_KEY" ; exit 1 )
-          [ -n "${{ vars.SSH_PRIVATE_KEY }}" ] && echo "::add-mask::${{ vars.SSH_PRIVATE_KEY }}" || ( echo "Required variable unset SSH_PRIVATE_KEY" ; exit 1 )
+          echo "::add-mask::${{ vars.SSH_PUBLIC_KEY }}"
+          echo "::add-mask::${{ vars.SSH_PRIVATE_KEY }}"
+          [ -n "${{ vars.SSH_PUBLIC_KEY }}" ] || ( echo "Required variable unset SSH_PUBLIC_KEY" ; exit 1 )
+          [ -n "${{ vars.SSH_PRIVATE_KEY }}" ] || ( echo "Required variable unset SSH_PRIVATE_KEY" ; exit 1 )
           [ -n "$MANIFEST_URI" ] || ( echo "Required variable unset MANIFEST_URI" ; exit 1 )
           [ -n "$MANIFEST_BRANCH" ] || ( echo "Required variable unset MANIFEST_BRANCH" ; exit 1 )
           [ -n "$MANIFEST_NAME" ] || ( echo "Required variable unset MANIFEST_NAME" ; exit 1 )
