workflow Thu Aug  1 13:24:23 CDT 2024

diff --git a/.github/workflows/images-build.yml b/.github/workflows/images-build.yml
--- a/.github/workflows/images-build.yml
+++ b/.github/workflows/images-build.yml
@@ -25,12 +25,15 @@ jobs:
   job-images-build:
     runs-on: [ self-hosted, almalinux ]
     steps:
-      - name: check and mark secrets
+      - name: check environment
         run: |
           echo "::add-mask::$SSH_PUBLIC_KEY"
           echo "::add-mask::$SSH_PRIVATE_KEY"
           [ -n "$SSH_PUBLIC_KEY" ] || ( echo "Required variable unset SSH_PUBLIC_KEY" ; exit 1 )
           [ -n "$SSH_PRIVATE_KEY" ] || ( echo "Required variable unset SSH_PRIVATE_KEY" ; exit 1 )
+          [ -n "$MANIFEST_URI" ] || ( echo "Required variable unset MANIFEST_URI" ; exit 1 )
+          [ -n "$MANIFEST_BRANCH" ] || ( echo "Required variable unset MANIFEST_BRANCH" ; exit 1 )
+          [ -n "$MANIFEST_NAME" ] || ( echo "Required variable unset MANIFEST_NAME" ; exit 1 )
       - name: secrets install ssh key
         run: |
           mkdir -p ${HOME}/.ssh
@@ -91,9 +94,6 @@ jobs:
       - name: repo init and sync
         shell: bash
         run: |
-          [ -n "$MANIFEST_URI" ] || ( echo "Required variable unset MANIFEST_URI" ; exit 1 )
-          [ -n "$MANIFEST_BRANCH" ] || ( echo "Required variable unset MANIFEST_BRANCH" ; exit 1 )
-          [ -n "$MANIFEST_NAME" ] || ( echo "Required variable unset MANIFEST_NAME" ; exit 1 )
           export PATH="${HOME}/.local/bin:${PATH}"
           repo init -u $MANIFEST_URI -b $MANIFEST_BRANCH -m $MANIFEST_NAME --no-clone-bundle --no-repo-verify
           # mkdir -p .repo/local_manifests
